### ISSUE TITLE
[SUGGETION] Remove empty sections

### ISSUE THREAD

**Issue by JanLin** [trustoverip/TIP0028-saturn-v#12]
https://trustoverip.github.io/TIP0028-saturn-v/
While sections are not populated hide them. Does not give good impression if have empty sections for visitors.

**Comment by vinomaster** [comment]
Agreed. However, this does expose an underlying issue -- the TF has yet to agree on the target outline for our content which should be step 1. See Issue #16 .

**Comment by vinomaster** [comment]
Tactical resolution is to remove all YAML references to ```placeholder.md```.
