### ISSUE TITLE
[SUGGETION] Intro explain other sections

### ISSUE THREAD

**Issue by JanLin** [trustoverip/TIP0028-saturn-v#13]
https://trustoverip.github.io/TIP0028-saturn-v/
This may be optional but like to give very short explanation of other sections for quick reference in the intro.

**Comment by vinomaster** [comment]
Most difficult if (1) we lack answer to Issue #16 and (2) we do not have a proposed description for each top level section. I will offer once again draft content given we lack alternative content.

We need to accompany suggestions with proposed solutions in the issues.

**Comment by JanLin** [comment]
This suggestion can be dropped. You did a good job on the rewrite.
