### ISSUE TITLE
[SUGGESTION] Tools and Best Practices

### ISSUE THREAD

**Issue by vinomaster** [trustoverip/TIP0028-saturn-v#25]
Based on the recent @JanLin presentation -- it would be helpful if we create  a new wiki page for `Tools and Best Practices`.

This SHOULD include IndyScan and others.

**Comment by JanLin** [comment]
Performed a pull request with a new page if you want accept it and then merge where you think is relevant.

**Comment by JanLin** [comment]
@vinomaster I tried to fix the image links but could not figure it out. Can you take a look? Thanks

**Comment by JanLin** [comment]
Fxied
